### ISSUE TITLE
getDayDetail 方法有点问题

### ISSUE THREAD

**Issue by Wjd97** [vsme/chinese-days#10]
getDayDetail('2024-09-14')返回的的是中秋节
{
    "date": "2024-09-14",
    "work": true,
    "name": "Mid-autumn Festival,中秋,1"
}
但是其实那天是调休，是工作日
好像涉及到调休的数据都不对

**Comment by vsme** [comment]
```
{
"date": "2024-09-14",
"work": true,
"name": "Mid-autumn Festival,中秋,1"
}
```
其中的 `work: boolean` 是判断是否需要上班的，`true` 需要上班 - 工作日，`false` 则休息；这个对象合起来描述的是 中秋节对应的工作日，也就是中秋的调休；如果 `work` 为 `false` 则是中秋节的休息日。
