### ISSUE TITLE
Outlook订阅后，提示订阅成功，但日历上没有任何显示

### ISSUE THREAD

**Issue by Chen-HT** [vsme/chinese-days#13]
Outlook订阅后，提示订阅成功，但日历上没有任何显示

**Comment by vsme** [comment]
测试了下，我这边可以正常展示
![image](https://github.com/user-attachments/assets/4523e7ea-1abe-4f72-b07d-6ab67751f932)

**Comment by vsme** [comment]
英文订阅也是 ok 的，订阅需要拉取时间，可能是 outlook 反应较慢，可以切换下日历时间之类的 等一会再看看
![image](https://github.com/user-attachments/assets/c3f38b12-48e2-475a-8d96-dd797b80dde9)
