### ISSUE TITLE
后续会不会考虑加上如儿童节之类的非放假类型的节日标识呢

### ISSUE THREAD

**Issue by pasBone** [vsme/chinese-days#8]
后续会不会考虑加上如儿童节之类的非放假类型的节日标识呢

**Comment by vsme** [comment]
这些应该属于“联合国假日”，在阳历中的日期比较固定，直接获取月份和日期就好了，比如 “儿童节”永远是 6月1日，这不像中国节日那样不固定，感觉并不太适合这个库。

**Comment by bush911** [comment]
能否加上数九呢？

**Comment by vsme** [comment]
> 能否加上数九呢？

不确定是从冬至逢壬日算，还是从冬至日算

**Comment by bush911** [comment]
> > 能否加上数九呢？
> 
> 不确定是从冬至逢壬日算，还是从冬至日算，可以考虑加上

昨天搜索了一下，好像大多数认为是冬至当天就是一九第一天，日人民报新闻也引用过。 当然冬至后逢壬日的报道也不少。 荣耀手机的日历好像是从冬至当天开始算的。要不就冬至当天开始吧，似乎这个更多一些
